### ISSUE TITLE
How to match an open order (perhaps add a user guide to the wiki)?

### ISSUE THREAD

**Issue by protinam** [DexyProject/wiki#1]
Unclear in the UI how to match (take) an existing signed order on the orderbook. Clicking the order doesn't seem to do anything. Tooltips, UI onboarding, or a DApp user guide here on the wiki would be very helpful.

**Comment by protinam** [comment]
Upon further investigation I realized that DEXY simply prevents self-trades - cool!

Can you add a tooltip over trades you placed to make this clear?

**Comment by decanus** [comment]
@protinam The orders you created are indicated with a little symbol to the left.
